resolver: lts-7.14
compiler: ghc-8.0

nix:
  enable: true
  pure: true
  packages: [zlib]
  # shell-file: shell.nix

packages:
- .

- ../spiros

- ../commands-core

- ../reified-bindings

extra-deps:
- spiros-0.0.0

- commands-core-0.0.0

- reified-bindings-0.0.0

- language-python-0.5.4
- recursion-schemes-5.0.1 # why? it's transitive.

