resolver: lts-6.1

packages:
- .

- ../spiros

- ../workflow-types

- ../commands-core
#- ../commands-frontend-DragonNaturallySpeaking

- ../reified-bindings

extra-deps:
- spiros-0.0.0

- workflow-types-0.0.0

- commands-core-0.0.0
#- commands-frontend-DragonNaturallySpeaking-0.0.0

#- language-python-0.5.4
