resolver: lts-5.17

packages:
- .

- ../workflow-types
- ../workflow-pure
- ../workflow-extra
- ../workflow-osx # TODO rm

- ../derive-monoid
- ../s-expression

extra-deps:

- workflow-osx-0.0.1
- workflow-pure-0.0.0
- workflow-extra-0.0.0

- derive-monoid-0.0.0
- s-expression-0.0.0

- language-python-0.5.2
- c-storable-deriving-0.1.3
- string-conv-0.1.1

# resolver: lts-3.5
# resolver: nightly-2015-09-21
# resolver: ghc-7.10.2
# resolver: ghcjs-0.1.0_ghc-7.10.2
# resolver:
#  name: custom-snapshot
#  location: "./custom-snapshot.yaml"

# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
# - location:
#    git: https://github.com/commercialhaskell/stack.git
#    commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
# - location: https://github.com/commercialhaskell/stack/commit/e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#   extra-dep: true
#  subdirs:
#  - auto-update
#  - wai
