resolver: nightly-2017-04-19 #lts-8.12
compiler: ghc-8.0.2

nix:
  # enable: true
  pure: true
  packages: [zlib]
  # shell-file: shell.nix

packages:
- .

- ../commands-core
- ../commands-frontend-DragonNaturallySpeaking
- ../commands-server-types
- ../commands-server-simple

#- ../workflow-types
#- ../workflow-pure
#- ../workflow-extra

# TODO these are platform specific
# - ../workflow-osx
# - ../workflow-windows

- ../reified-bindings
#- ../enumerate
#- ../derive-monoid
#- ../s-expression

extra-deps:
- spiros-0.0.0

- commands-core-0.0.0
- commands-frontend-DragonNaturallySpeaking-0.0.0
- commands-server-types-0.0.0
- commands-server-simple-0.0.0

- workflow-types-0.0.1
- workflow-pure-0.0.1
- workflow-extra-0.0.1

# TODO these are platform specific
#- workflow-osx-0.0.1
- workflow-windows-0.0.0

- enumerate-0.2.2
- derive-monoid-0.0.1
- s-expression-0.0.0

- Earley-0.12.0.0
- language-python-0.5.4
- c-storable-deriving-0.1.3
- string-conv-0.1.1
#- optparse-generic-0.13.2.0
- recursion-schemes-5.0.1 #?
