resolver: lts-5.17

packages:
- .

- ../reified-bindings
- ../derive-monoid
- ../s-expression

extra-deps:

- reified-bindings-0.0.0
- derive-monoid-0.0.0
- s-expression-0.0.0

- language-python-0.5.2
- c-storable-deriving-0.1.3
- string-conv-0.1.1
- optparse-generic-1.1.1
