resolver: lts-7.14
compiler: ghc-8.0

nix:
  enable: true
  pure: true
  packages: [zlib]
  # shell-file: shell.nix

packages:
- .
- ../spiros

- ../workflow-types

extra-deps:
- spiros-0.0.0

- workflow-types-0.0.0
