resolver: nightly-2017-04-19 # lts-8.12
compiler: ghc-8.0.2

nix:
#  enable: true
  pure: true
  packages: [zlib]

packages:
- .
- ../spiros
#- ../workflow-types

extra-deps:
- spiros-0.0.0
- workflow-types-0.0.1
