resolver: nightly-2017-11-23   # the last ghc-8.2.1 nightly 

nix:
  enable: false
  pure: true
  packages:
  - zlib

packages:
- commands-core/
- commands-frontend-DragonNaturallySpeaking/
- commands-server-types/
- commands-server-simple/

# - ../workflow/workflow-types/
# - ../workflow/workflow-pure/
# - ../workflow/workflow-extra/
# - ../workflow/workflow-windows/

# - ../enumerate/enumerate 
# - ../enumerate/enumerate-function

# - ../reified-bindings
# - ../derive-monoid
# - ../s-expression

- location:
    git:    https://github.com/sboosali/spiros
    commit: 0c5f3584e73ae3e4c00b0a142d2024c241ac3032
  extra-dep: true
  subdirs: [.]

- location:
    git:    https://github.com/sboosali/workflow
    commit: 70a894d943253c8989496fdbe1d3725cb8aaf165
  extra-dep: true
  subdirs:
  - workflow-types 
  - workflow-pure
  - workflow-extra 
  - workflow-windows 

extra-deps:
# - spiros-0.0.0

# - commands-core-0.0.0
# - commands-frontend-DragonNaturallySpeaking-0.0.0
# - commands-server-types-0.0.0
# - commands-server-simple-0.0.0

# - workflow-pure-0.0.0
# - workflow-extra-0.0.0
# - workflow-windows-0.0.0

# - enumerate-0.2.1
# - derive-monoid-0.0.0
# - s-expression-0.0.0

- Earley-0.12.0.1
- language-python-0.5.4
- c-storable-deriving-0.1.3
- string-conv-0.1.1
- optparse-generic-1.1.3
- recursion-schemes-5.0.1 
