resolver: nightly-2017-12-09 
# compiler: ghc-8.2.2 

nix:
  enable: false
  pure: true
  packages: [zlib]
  # shell-file: shell.nix

build:
  library-profiling: False
  executable-profiling: False

packages:
- .

- ../spiros

- ../reified-bindings

extra-deps:
- spiros-0.0.0

- reified-bindings-0.0.0

- language-python-0.5.4
- c-storable-deriving-0.1.3
- string-conv-0.1.1

#- optparse-generic-1.1.1
- recursion-schemes-5
- Earley-0.12.0.0
